Show dialog message if URL is malformed.
googlefonts/fontra pull request #1623
Opened 2024-08-28 13:30 UTC by ollimeier

Fixes #1616

2024-08-29 07:15 UTC, justvanrossum reviewed
One small comment. Otherwise looks fine.

2024-08-29 07:15 UTC, justvanrossum commented on src/fontra/client/core/utils.js
> +    return false;
```suggestion
    return null;
```

2024-08-29 07:29 UTC, justvanrossum approved these changes

2024-08-30 06:28 UTC, justvanrossum requested changes
I just now tried it myself, but while there is a dialog now, there is a different error after this, prevnting the URL to be updated later:

<img width="929" alt="image" src="https://github.com/user-attachments/assets/6d76c9f8-1761-4b78-ab27-f12f6e4d5093">

Paste a malfored URL in a new tab, dismiss the dialog, then add text to the text entry field. Notice how the URL does not get updated: it stays at the malformed URL.

2024-08-30 06:50 UTC, ollimeier commented
> I just now tried it myself, but while there is a dialog now, there is a different error after this, prevnting the URL to be updated later:
> 
> <img alt="image" width="929" src="https://private-user-images.githubusercontent.com/4246121/363064269-6d76c9f8-1761-4b78-ab27-f12f6e4d5093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDA5MjAsIm5iZiI6MTcyNTAwMDYyMCwicGF0aCI6Ii80MjQ2MTIxLzM2MzA2NDI2OS02ZDc2YzlmOC0xNzYxLTRiNzgtYWIyNy1mMTJmNmU0ZDUwOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDY1MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY1YmEyY2VlYzIxNGU4Y2NhYTc1MWU1YjFhYWEwMjM4NjlkOTcxOTQxZGUwYmE0NGU3MjNkZjBlMzg3NjQyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GYCzZF-OvLDRSnX6WJC6IAxPrXb-VlPdZpPInvaGWUI">
> Paste a malfored URL in a new tab, dismiss the dialog, then add text to the text entry field. Notice how the URL does not get updated: it stays at the malformed URL.

Thanks for finding this. I fixed it.

2024-08-30 07:19 UTC, justvanrossum approved these changes

2024-08-30 08:12 UTC, merged